from tkinter import *
top=Tk()
top.geometry("1400x800")
top.title('CLASS')
top.config(bg="black")
welcome=Label(top,text="Welcome Our Page",font=('TimesNewRoman',30,'italic'),bg="black",fg="white")
welcome.place(x=500,y=75)
def login():
    Kit=Frame(top,bg="blue",height=700,width=400)
    Kit.pack(fill=X)
    label1=Label(Kit,text="LOGIN PAGE",font=('TimesNewRoman',50,'italic'),bg="blue",fg="white")
    label1.place(x=500,y=100)
    label1=Label(Kit,text="Username",font=('TimesNewRoman',35,'italic'),bg="blue",fg="white")
    label1.place(x=500,y=300)
    label1=Label(Kit,text="Password",font=('TimesNewRoman',35,'italic'),bg="blue",fg="white")
    label1.place(x=500,y=415)
    label1=Label(Kit,text="Dont have an account?",font=('TimesNewRoman',30,'italic'),bg="blue",fg="white")
    label1.place(x=400,y=600)
    label1=Label(Kit,text="Login",font=('TimesNewRoman',30,'italic'),bg="pink",fg="purple")
    label1.place(x=650,y=500)
    label1=Label(Kit,text="sign in",font=('TimesNewRoman',30,'italic'),bg="pink",fg="purple")
    label1.place(x=900,y=600)
    box=Entry(Kit,text="",font=('TimesNewRoan',15,'italic'),fg="red")
    box.place(x=800,y=315,width=300,height=50)
    box=Entry(Kit,text="",font=('TimesNewRoan',15,'italic'),fg="red")
    box.place(x=800,y=425,width=300,height=50)
button=Button(top,text='GET STARTED',font=('TimesNewRoman',15,'italic'),bg="white",fg="black",activeforeground="pink",activebackground="yellow",command=login)
button.place(x=550,y=400,height=100,width=200)
top.mainloop()
